### ISSUE TITLE
CI via Bootstrapping supports multiple inputs as tagMatrixList

### ISSUE THREAD

**Issue by Puriney** [GuangchuangYu/ChIPseeker#5]
5. Enable `getTagCount` function to use `conf` (confidence interval) and estimate CI via bootstrapping. 
10. Enable `plotAvgProf` function to plot tagMatrixList
20. Enable `plotAvgProf2` function to plot tagMatrixList

**Comment by GuangchuangYu** [comment]
I add facet and free_y parameters, see https://github.com/GuangchuangYu/ChIPseeker/commit/cf2bfb6e661472ebd46607755c881d7c4c6bdc50

If facet = "none", all in one figure.
If facet = "row" or "column", separate to several figures and align by row or column.

free_y parameter only has meaning when input is a list and facet != "none".
If free_y = TRUE, y scale is proportion to average of profile, otherwise, it is fixed, as when facet="none".
